###
//COUNTRY
###
POST http://localhost:3000/country
Content-Type: application/json

{
    "name":"France",
    "code":"FRA"
}
###
GET http://localhost:3000/country
###
###
GET http://localhost:3000/country/4
###
//BRAND
###
GET http://localhost:3000/brand
###
POST http://localhost:3000/brand
Content-Type: application/json

{
    "name":"FIAT",
    "foundationDate":"1899-07-11T00:00:00.00Z",
    "country":2,
    "bio":"Fiat Automobiles S.p.A. (UK: /ˈfiːət, -æt/ FEE-ət, -⁠at, US: /-ɑːt/ -⁠aht, Italian: [ˈfiːat]; originally FIAT, Italian: Fabbrica Italiana Automobili di Torino; lit. 'Italian Automobiles Factory of Turin') is an Italian automobile manufacturer, formerly part of Fiat Chrysler Automobiles, and since 2021 a subsidiary of Stellantis through its Italian division Stellantis Europe. Fiat Automobiles was formed in January 2007 when Fiat S.p.A. reorganized its automobile business,[2] and traces its history back to 1899, when the first Fiat automobile, the Fiat 4 HP, was produced"
}
###
GET http://localhost:3000/brand/1

###
//VEHICLE TYPE
###
POST http://localhost:3000/vehicleType
Content-Type: application/json

{
    "name":"Automóvel",
    "country":1
}
###
GET http://localhost:3000/vehicleType
###
//USERS
###
GET http://localhost:3000/user


###
# @name userCreated
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "firstName":"Gustavo",
    "lastName":"Moura",
    "email":"gustavomoura.dev@gmail.com",
    "document":"49722630830",
    "birthdate":"1999-02-26T15:00:00.000Z",
    "password":"Senha@123",
    "passwordConfirmation":"Senha@123"
}

###
@userId = {{userCreated.response.body.id}}
###
GET http://localhost:3000/user/{{userId}}


###
POST http://localhost:3000/address/{{userId}}
Content-Type: application/json

{
    "number":99,
    "street":"Rua Camburiú",
    "zipCode":"05060020",
    "complement":"Casa 1",
    "neighbourhood":"Vila Ipojuca",
    "city":"São Paulo",
    "district":"São Paulo",
    "country":"BR"
}
