//USERS
###
GET http://localhost:3000/user


###
# @name userCreated
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "firstName":"Gustavo",
    "lastName":"Moura",
    "email":"gustavomoura.dev@gmail.com",
    "document":"49722630830",
    "birthdate":"1999-02-26T15:00:00.000Z",
    "password":"Senha@123",
    "passwordConfirmation":"Senha@123"
}

###
@userId = {{userCreated.response.body.id}}
###
GET http://localhost:3000/user/{{userId}}


###
POST http://localhost:3000/address/{{userId}}
Content-Type: application/json

{
    "number":99,
    "street":"Rua Camburiú",
    "zipCode":"05060020",
    "complement":"Casa 1",
    "neighbourhood":"Vila Ipojuca",
    "city":"São Paulo",
    "district":"São Paulo",
    "country":"BR"
}
